// Generated by matugen. Overwritten on every wallpaper switch.
//
// Installed into the mango-sddm greeter by /usr/local/bin/sddm-theme-sync, which
// refuses anything that differs from this template by more than the colour
// literals — so keep every line that is not a colour slot exactly as it is, and
// re-run `sudo system/sddm/install.sh` after editing, or the sync stops working.
// See mango-dotfiles/system/sddm/. (No slot syntax in these comments: Tera
// expands it here too, and a malformed one fails the whole matugen run.)
//
// Plain QtObject, not a singleton: Main.qml instantiates it from the same
// directory, which means the theme needs no qmldir and no QML2_IMPORT_PATH.

import QtQuick

QtObject {
    property color background: "{{colors.background.default.hex}}"
    property color error: "{{colors.error.default.hex}}"
    property color on_error: "{{colors.on_error.default.hex}}"
    property color on_primary: "{{colors.on_primary.default.hex}}"
    property color on_surface: "{{colors.on_surface.default.hex}}"
    property color on_surface_variant: "{{colors.on_surface_variant.default.hex}}"
    property color outline: "{{colors.outline.default.hex}}"
    property color outline_variant: "{{colors.outline_variant.default.hex}}"
    property color primary: "{{colors.primary.default.hex}}"
    property color primary_container: "{{colors.primary_container.default.hex}}"
    property color scrim: "{{colors.scrim.default.hex}}"
    property color surface: "{{colors.surface.default.hex}}"
    property color surface_container: "{{colors.surface_container.default.hex}}"
    property color surface_container_high: "{{colors.surface_container_high.default.hex}}"
    property color surface_container_highest: "{{colors.surface_container_highest.default.hex}}"
}
