#!/bin/sh
# Generated by matugen. Edit the template, not this file.
exec claudebar --icon '' \
  --color-low      '{{colors.term2.default.hex}}' \
  --color-mid      '{{colors.term3.default.hex}}' \
  --color-high     '{{colors.term1.default.hex}}' \
  --color-critical '{{colors.error.default.hex}}'
